### ISSUE TITLE
Nectar instance difficulties

### ISSUE THREAD

**Issue by thomshaw92** [NeuroDesk/neurodesktop#123]
It's a little tricky knowing where the files are in the nectar cloud when transferring them - the info should be a little clearer in the docs or a popup would be nice to know where the files are.

Also, the Singularity bind paths for /neurodesktop-storage don't work on nectar. I know these are two *noted* issues in the documentation, but it has changed all my workflows, things not working, etc etc

**Comment by aswinnarayanan** [comment]
Thanks @thomshaw92, I'll chase up the nectar file location with the team and get back

**Comment by aswinnarayanan** [comment]
@thomshaw92 Would a "file-uploads" symlink on desktop be clear enough? Any suggestions?

**Comment by stebo85** [comment]
we could change the default location for the upload to be desktop as well?

**Comment by thomshaw92** [comment]
Would be good either way :)

**Comment by aswinnarayanan** [comment]
Have feedbacked this to Andy. 
The performance issues seems to be due to the guacmole rdp virtual drive. Nectar has plans to provide persistent storage as the long term solution so this will likely be resolved by the development on that project.

For the findability, VDS guacamole is managed by their setup, So we'll need to let the Nectar team resolve this, so waiting on external input. Will chase up sometime after the holidays

**Comment by stebo85** [comment]
This is now addressed - we added a "transfer" symlink to the desktop.
