### ISSUE TITLE
jupyterlmod not finding modules

### ISSUE THREAD

**Issue by aswinnarayanan** [NeuroDesk/neurodesktop#168]

**Comment by stebo85** [comment]
is this a problem in the latest desktop image after the modifications for kubernetes?

**Comment by aswinnarayanan** [comment]
Latest image (images). I'm rolling back through the builds to see where it was working

**Comment by stebo85** [comment]
ok - let me know if I can help.

**Comment by aswinnarayanan** [comment]
Found the problem

In the current build, `MODULEPATH` is generated dynamically using `/cvmfs/neurodesk.ardc.edu.au/neurodesk-modules/*` in `/opt/neurodesktop/environment_variables.sh`

Running this in .bashrc, ipython_start or jupyter_notebook_config.py doesn't seem to work, as it may be too late.

before-notebook.sh works for local but not for k8s

Lmod was working in jupyter-neurodesktop-proxy and older neurodesktop because MODULEPATH was hardcoded into the Dockerfile

**Comment by aswinnarayanan** [comment]
Any ideas? Should we hardcode it in for the time being?

**Comment by stebo85** [comment]
ok, then let's hard-code it for now until we have a better solution

**Comment by aswinnarayanan** [comment]
I added the neurodesk-module as the initial modulepath. This gets overwritten later. Doesn't look too bad actually

![image](https://github.com/NeuroDesk/neurodesktop/assets/25297584/f8875e8c-4e60-486c-a566-88100468ed06)

**Comment by stebo85** [comment]
this will not work! The module names are now diffusion_imaging/fsl and it will break the current examples

**Comment by aswinnarayanan** [comment]
It won't break the actual modules, cause we still overwrite the modulepath on startup.
This was just for the jupyterlmod to preload its list of modules. I think it's just recursively looking for module files in the modulepath, and adding them as a list. It seemed to have picked them up on testing

**Comment by stebo85** [comment]
hm, ok - I will test - when I tried this the last time the jupyter notebooks were not working.

**Comment by aswinnarayanan** [comment]
You are correct, it's broken the paths on the notebooks. I didn't realize cause the modulepath was completely broken before.
We'll need to hardcode the MODULEPATH as an ENV

**Comment by stebo85** [comment]
that's a good solution for now :) We only need to change the MODULEPATH if we add a new category. An alternative idea we could try: 


We do this, so we get categories in LMOD:
ENV MODULEPATH=/cvmfs/neurodesk.ardc.edu.au/neurodesk-modules/bids_apps:/cvmfs/neurodesk.ardc.edu.au/neurodesk-modules/body:/cvmfs/neurodesk.ardc.edu.au/neurodesk-modules/data_organisation:/cvmfs/neurodesk.ardc.edu.au/neurodesk-modules/diffusion_imaging:/cvmfs/neurodesk.ardc.edu.au/neurodesk-modules/electrophysiology:/cvmfs/neurodesk.ardc.edu.au/neurodesk-modules/functional_imaging:/cvmfs/neurodesk.ardc.edu.au/neurodesk-modules/hippocampus:/cvmfs/neurodesk.ardc.edu.au/neurodesk-modules/image_reconstruction:/cvmfs/neurodesk.ardc.edu.au/neurodesk-modules/image_registration:/cvmfs/neurodesk.ardc.edu.au/neurodesk-modules/image_segmentation:/cvmfs/neurodesk.ardc.edu.au/neurodesk-modules/machine_learning:/cvmfs/neurodesk.ardc.edu.au/neurodesk-modules/molecular_biology:/cvmfs/neurodesk.ardc.edu.au/neurodesk-modules/phase_processing:/cvmfs/neurodesk.ardc.edu.au/neurodesk-modules/programming:/cvmfs/neurodesk.ardc.edu.au/neurodesk-modules/quality_control:/cvmfs/neurodesk.ardc.edu.au/neurodesk-modules/quantitative_imaging:/cvmfs/neurodesk.ardc.edu.au/neurodesk-modules/rodent_imaging:/cvmfs/neurodesk.ardc.edu.au/neurodesk-modules/shape_analysis:/cvmfs/neurodesk.ardc.edu.au/neurodesk-modules/spectroscopy:/cvmfs/neurodesk.ardc.edu.au/neurodesk-modules/spine:/cvmfs/neurodesk.ardc.edu.au/neurodesk-modules/statistics:/cvmfs/neurodesk.ardc.edu.au/neurodesk-modules/structural_imaging:/cvmfs/neurodesk.ardc.edu.au/neurodesk-modules/visualization:/cvmfs/neurodesk.ardc.edu.au/neurodesk-modules/workflows

This doesn't work because then the category name becomes part of the tool name
MODULEPATH=/cvmfs/neurodesk.ardc.edu.au/neurodesk-modules/

BUT, this could work, because these are the flat module files before being reorganized in categories:
MODULEPATH=/cvmfs/neurodesk.ardc.edu.au/containers/modules/

This might break the categories when running ml av on the command line, but if we overwrite this with sourcing the bashrc  it might work

**Comment by aswinnarayanan** [comment]
> BUT, this could work, because these are the flat module files before being reorganized in categories:
> MODULEPATH=/cvmfs/neurodesk.ardc.edu.au/containers/modules

This might be a good option.

The start up script will override it with categorized modules for so "ml av" works on command line.

The only possible issue is that ipython, jupyterlmod and notebooks will still continue to use the flat module list.
But I don't think they use the categories in any way. `lmod.avail()` just renders a flat list, so we might be fine

**Comment by stebo85** [comment]
yes, let's try that :)
