### ISSUE TITLE
CVMFS test failure

### ISSUE THREAD

**Issue by aswinnarayanan** [NeuroDesk/neurodesktop#207]
Since 22nd Jan
https://github.com/NeuroDesk/neurodesktop/actions/runs/7614875725

**Comment by stebo85** [comment]
Yes, Perth is down and they are having problems starting instances :(


Thank you

Steffen

--

W: https://mri.sbollmann.net<https://mri.sbollmann.net/>  | W: https://www.neurodesk.org<https://www.neurodesk.org/>  | T: https://twitter.com/sbollmann_MRI  | G: https://github.com/stebo85

Book meeting: https://calendly.com/s-bollmann/meeting

________________________________
From: Aswin Narayanan ***@***.***>
Sent: Thursday, February 1, 2024 12:11:16 PM
To: NeuroDesk/neurodesktop ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NeuroDesk/neurodesktop] CVMFS test failure (Issue #207)


Since 22nd Jan
https://github.com/NeuroDesk/neurodesktop/actions/runs/7614875725
