### ISSUE TITLE
Difficulty opening Neurodesk packages in Neurodesktop

### ISSUE THREAD

**Issue by salilabwfu** [NeuroDesk/neurodesktop#241]
Hello. I recently installed neurodesk but am having some trouble getting the individual packages to work. In the neurodesktop environment, I can open most things (like office software and internet), but when I select anything in the neurodesk menu, I get a terminal window that produces an error message before closing itself. The error comes after it attempts to launch the container (in this case fmriprep):

`FATAL         exec /usr/bin/cat failed: invalid argument`
`FATAL           exec /bin/bash failed: invalid argument`

Is this a bug or am I doing something wrong? I've tried this on several different computers now with different versions of MacOS and have gotten the same result. The machine I have mostly tested on has an M1 processor with MacOS 13.6.1.

Thank you in advance for your help!
Anthony

**Comment by stebo85** [comment]
Dear @salilabwfu,

This is, unfortunately, a recent bug of Docker on Apple Silicone. The workaround is to use Podman instead of Docker.

So install podman (https://podman.io/) and then select podman in the neurodesk app:
<img width="700" alt="image" src="https://github.com/user-attachments/assets/4cdebd37-438a-4bbd-a063-e1e5fa63510c">

Let us know if this works
and we very much hope this bug can be fixed soon.
