### ISSUE TITLE
work on poc for jupyter desktop so we can run a demo on mybinder

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurodesktop#55]

**Comment by TomEmotion** [comment]
Aha! I've been using Jupyter notebooks on the old VNM within my conda environment, mainly because last time I checked I preferred it to JupyterLab. But haven't tried the more recent desktop app. Anything in particular that's needed?

Also, since this is based on conda, would it be integrated with our install of that, or just sit there as a completely standalone app?

**Comment by stebo85** [comment]
yes, this is the "teaching" edition of neurodesktop we are working on where users don't need to install docker on their computer :) It's still early days but maybe we can show something there next meeting.

**Comment by aswinnarayanan** [comment]
### Some progress...

Got neurodesktop and guacamole working with jupyter-server-proxy

https://github.com/NeuroDesk/jupyter-remote-desktop-proxy/tree/jupyterserverproxy

Whats working on MyBinder public:
- [x] Guacamole + Tomcat
- [x] Neurodesktop lxde
- [x] VNC

We can launch with MyBinder using: https://mybinder.org/v2/gh/NeuroDesk/jupyter-remote-desktop-proxy/jupyterserverproxy


### Current roadblocks 

(unsurprisingly) the public mybinder doesn't run their docker containers in privileged mode. So the desktop is able to download the neurocontainers, but fails on starting them up (the startup command window will disappear due to privilege error)

We can install things as root, but can't start up anything with sudo for the moment. (Might be possible to recompile xrdp for non-root, I can have a look into this)

**Comment by stebo85** [comment]
Oh wow - this is super cool! 

I have a look if I can find a way of mounting CVMFS (this should be possible without root or the privileged option: https://github.com/cvmfs/cvmfsexec#running-from-docker) and then we can run singularity without privileges because the containers are flat and unpacked. We might have to build singularity with ./mconfig --without-suid?

**Comment by aswinnarayanan** [comment]
That would be amazing. I'll look into xrdp then.
Does cvmfs need sudo to start up?

**Comment by aswinnarayanan** [comment]
I experimented around with singularity in docker and cvmfs

For running without privileged  mode, so far I've found the minimum requirements to be
```
--cap-add SYS_ADMIN
--security-opt apparmor:unconfined
--device=/dev/fuse
```
Singularity requires the first two
The cvmfs mount requires all three

**Comment by stebo85** [comment]
This is great to know! Thank you so much for finding this out Aswin.

**Comment by aswinnarayanan** [comment]
Got neurodesktop and containers working on a binderhub on oracle cloud kubernetes cluster.

Some needed enhancements:
- Switch from VNC to RDP
- UID/GID mapping
- Further container security lockdown
- Some kind of login or authentication layer (OpenID etc)


Our current method of uid/gid mapping is introducing challenges and roadblocks to solutions all around.
We may need to find a better method, I'm trying out a couple of options

**Comment by aswinnarayanan** [comment]
PoC on JupyterHub and MyBinder working. Closing
