### ISSUE TITLE
RDP and VNC do not work after I stop and start the neurodesktop docker container

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neurodesktop#57]
Dear @aswinnarayanan ,

I had the pleasure to play with neurodesktop, and I must say that I'm delighted. You really did an impressive job of putting so much functionality into it. In a sense, putting all of VNC inside a container :-) Well done!

It works very smoothly, and maybe the only issue I found until now is that RDP and VNC do not work after I restart the neurodesktop container (running "docker stop <container ID>" and then "docker  start <container ID>"). I'm not sure if the problem is specific to NECTAR instances, where I run Neurodesktop, so you're welcome to try it out also on other platforms. Notice that the command line interface (SSH) does work after a container restart.

We found out that restarting the container is an important functionality for us, as sometimes things stop working (like any computer), and the only solution that preserves the state of the container is restarting it. I also used the restart functionality when I setup VNM on NECTAR in Swinburne: after I ran some Swinburne-specific configurations inside a running VNM container, I stopped the container, and created a snapshot of the NECTAR instance. When somebody then request from me access to VNM, I simply launched new instances from that snapshot, and started the stopped VNM. I want to do the same with Neurodesktop, but for that, I need the start/stop functionality to work.

Thanks ahead for your assistance,
Oren

**Comment by stebo85** [comment]
Dear @civier,

Containers are not designed to be persistent - they are designed to be ephemeral. I do not see a feasible way of achieving a use-case where one would keep the container for a long time and modify settings and tools inside the container. If you do see a way of doing this you are welcome to contribute a proof of concept.

Kind regards
Steffen

**Comment by stebo85** [comment]
Dear @civier,

no, containers have a short lifespan in webservices. They are continuously updated and run only for short amounts of time. The persistent webservice illusion is created using Orchestration engines like Kubernetes that manage the lifecycle of containers, a good starting point to understand this is here: https://en.wikipedia.org/wiki/Kubernetes 

I hope this helps
Cheers
Steffen

**Comment by civier** [comment]
> Dear @civier,
> 
> no, containers have a short lifespan in webservices. They are continuously updated and run only for short amounts of time. The persistent webservice illusion is created using Orchestration engines like Kubernetes that manage the lifecycle of containers, a good starting point to understand this is here: https://en.wikipedia.org/wiki/Kubernetes
> 
> I hope this helps Cheers Steffen

Thanks @stebo85 
BTW, what is it in the technology/design of docker that does not fit well with persistency?
We used the VNM as a persistent desktop for months with hardly any problem. And if something stopped working after all, we just restarted the container (docker stop and start) and all good.

**Comment by aswinnarayanan** [comment]
Hi @civier. I've applied some changes that may resolve this VNC/RDP issues
Can you please test on the latest neurodesktop-dev and let me know

**Comment by civier** [comment]
What do you mean by the latest neurodesktop-dev? Did you upload it to
Docker hub (what is the image name exactly?), Or should I build it from
Neurodesktop GitHub?

Oren

**Comment by civier** [comment]
> Also (unless its running some job), running an interactive desktop persistently also uses up the underlying cloud resource while the desktop is not being used.

Hi @aswinnarayanan

Regarding the above comment you made -- a NECTAR instance for example can be shelved (effectively, creating a snapshot of it) and then restored. Right now it is not simple for users to do it on their own, but I guess it can be automated. This way users would be able to free the resources of their instance, and return to work on it later. But this of course will require to stop and then start Neurodesktop.

I'm pretty sure that something like this is already automated in commercial cloud services. Can you do it easily on the Oracle cloud that you're using? Maybe @stebo85 knows.

**Comment by TomEmotion** [comment]
Please ignore my question regarding the updating - I see it is addressed in the Documentation. Thanks.

**Comment by civier** [comment]
> The desktop container has to be updated very often to make sure that new containers get added

Dear @stebo85 

Can you clarify why a neurodesktop update is necessary for new containers to be added? Can't we come with a mechanism that add them dynamically? I think already now there is no issue with using new containers through the command line (correct me if wrong), so we probably can also find a solution for the menu entries. Can't we?

Best,
Oren

**Comment by stebo85** [comment]
>  Do you know if there is any option to make Github re-email edited posts? 
no I am not aware of a feature like this

> Containers are not designed for users to modify settings and tools inside
This is quite clear. As Tom said, we will discuss it in SNI to see how it affects our workflows.
I just have one question: is this something specific to Docker, Singularity, or do you see it as a general issue with container technology?
It is a general aspect of container technology. Containers are designed to be stateless.


> Containers are not designed to be run for a long time
Some of the users in SNI would like to run Neurodesktop for a long time, even if they don't change any permanent things inside. This is for the mere convenience of not having to open all the graphical applications again, for example, if you were in the middle of a complex analysis with many windows open, or if you changed many temporary settings through the GUI.
How long can a container be run for safely? Can you give an approx. number of days?
You can run in until something crashes inside the container. This will depend on the use of the users and how lightweight we keep the desktop container (the less things can go wrong). Then a restart of the container would be necessary and GUI changes will be gone. 
 
> Starting and stopping a container
From what you're saying, I'm not sure if "docker stop" and "docker start" are problematic by themselves? Do you think that containers are less stable or perform worse after restarting them in this way?
docker stop and start should work now with the desktop container and the reason it wasn't working earlier was a bug. Since we currently do not have the resources to support this workflow I am sure there are more bugs that would need to be fixed. The question we need to ask is #58 - it is possible to support this but it will cost time that we cannot spend on other things. Currently there is no contribution to the code from Swinburne or Sydney and we have to accept that Aswin and I have limited capacity in implementing and supporting features.
