### ISSUE TITLE
firefox seems to have trouble with neurodesktop? 404 when opening from docker in windows 10

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurodesktop#70]

**Comment by aswinnarayanan** [comment]
Working on 
- Windows 11
- Firefox: 94.0.2 (64-bit)
- Docker Desktop 4.2.0 (70708)

**Comment by stebo85** [comment]
yes, working on Windows 10 for me as well (and Angie tested as well), but @mrikasper got this error. Need to continue troubleshooting on Lars's notebook.

**Comment by stebo85** [comment]
This happens in Firefox 94.0.2 (64 bit) windows 10 home

**Comment by stebo85** [comment]
Access Error: 404 -- Not Found
Cannot Locate document : /

**Comment by stebo85** [comment]
This bug could be related to https://www.enpass.io/support/kb/security/enpass-browser-extension-is-not-working-due-to-sophos-antivirus/

in addition the clipboard support in firefox is not good

-> maybe recommend to use edge?

**Comment by stebo85** [comment]
closing this here -> will replace with local jupyter client

**Comment by uxhao-o** [comment]
This issue could be caused by your local (windows) Jupyter service. Local Jupyter run on 8888 port and the Jupyter sevice port in Neurodesk docker also map to 8888. So, when you use '127.0.0.1:8888' could to obtain local jupyter rather than Jupyter service of Neurodesk.  You can modify the docker run command :
```bash
docker run --shm-size=1gb -it --privileged --user=root --name neurodesktop -v C:/neurodesktop-storage:/neurodesktop-storage --mount source=neurodesk-home,target=/home/jovyan -p 8889:8888 -e NEURODESKTOP_VERSION=2025-06-10 vnmd/neurodesktop:2025-06-10
```
ie., 8888:8888 to 8889:8888
