### ISSUE TITLE
laggy experience across browsers on macbook pro

### ISSUE THREAD

**Issue by kel-github** [NeuroDesk/neurodesktop#71]
Things like re-sizing windows, scrolling in VS code etc is very laggy/slow -
Consistent across browsers: Firefox 94.02, Chrome 96.0.4664.55, Safari 14.1.2 on Macbook pro (Early 2015, Big Sur, 2.7 Ghz Dual-Core Intel i5, 8GB memory)

**Comment by stebo85** [comment]
I tested a few things and the problem is docker running on Mac.

Solutions for the problem: 
1) use Visual studio code on the mac to access neurodesktop: https://neurodesk.github.io/docs/neurodesktop/visual-studio-code/ (this will help because vs code runs natively on mac)
2) run neurodesktop on a remote server and connect to it via the browser

the problem is not the browser performance in the browser!
